// Generated by wrangler - defines Cloudflare bindings
// Run `npm run cf-typegen` to regenerate

interface Env {
  AI: Ai;
  JOB_DO: DurableObjectNamespace;
  USER_DO: DurableObjectNamespace;
  METRICS: KVNamespace;
  PRODUCTS: KVNamespace;
  X402_NETWORK: "mainnet" | "testnet";
  X402_SERVER_ADDRESS: string;
  X402_FACILITATOR_URL: string;
  CLAUDE_EXECUTOR: "workers-ai" | "anthropic" | "queue";
  MAX_JOB_DURATION_MS: string;
  ANTHROPIC_API_KEY?: string;
}
